# Generated by Django 4.2 on 2023-04-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feat',
            new_name='feature',
        ),
    ]
