# Generated by Django 4.2 on 2023-04-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feature',
        ),
    ]
